CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_GATT_CLIENT=y # can receive responses, indications and notifications. important for cert exchange
CONFIG_BT_DEVICE_NAME="Zephyr GATT Write"

# CONFIG_BT_BUF_ACL_RX_SIZE=255
# CONFIG_BT_BUF_ACL_TX_SIZE=251
# CONFIG_BT_BUF_CMD_TX_SIZE=255
# CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=255
#
# CONFIG_BT_L2CAP_TX_MTU=247

CONFIG_LOG=y
# CONFIG_BT_LOG_LEVEL_DBG=y
# CONFIG_BT_ATT_LOG_LEVEL_DBG=y
# CONFIG_BT_GATT_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=2048
## Number of buffers available for ATT prepare write, setting this to 0 disables GATT long/reliable writes.
#zephyr/doc/connectivity/bluetooth/api/audio/bluetooth-le-audio-arch.rst
##Read long Characteristic Value by setting :kconfig:option:`CONFIG_BT_ATT_PREPARE_COUNT` to a non-zero value.
#
##  MIN(BT_ATT_MAX_ATTRIBUTE_LEN, CONFIG_BT_ATT_PREPARE_COUNT * BT_ATT_BUF_SIZE));
#  For example,
#  if your characteristic is 70, assuming MTU (BT_ATT_BUF_SIZE) is 23, you need at least 4 prepare writes (4*23=92 > 70)
#     << this is not correct, i tried with 3 and it worked, see below
#   But on the other hand there is this code for the ASCS
#   /* Verify that the prepare count is large enough to cover the maximum value we support a client
#    * writing
#     */
#     BUILD_ASSERT(
#       (BT_ATT_BUF_SIZE - NTF_HEADER_SIZE) >= ASE_BUF_SIZE ||
#        DIV_ROUND_UP(ASE_BUF_SIZE, (BT_ATT_BUF_SIZE - NTF_HEADER_SIZE)) <= CONFIG_BT_ATT_PREPARE_COUNT,
#       "CONFIG_BT_ATT_PREPARE_COUNT not large enough to cover the maximum supported ASCS value");
#
#       Al this is defined in att_internal.h as:
#       #define BT_ATT_BUF_SIZE MAX(BT_LOCAL_ATT_MTU_UATT, BT_LOCAL_ATT_MTU_EATT)
#           #define BT_LOCAL_ATT_MTU_EATT MIN(BT_L2CAP_SDU_RX_MTU, BT_L2CAP_SDU_TX_MTU)
#               #define BT_L2CAP_SDU_RX_MTU (BT_L2CAP_RX_MTU - BT_L2CAP_SDU_HDR_SIZE)
#                   /** Maximum Transmission Unit (MTU) for an incoming L2CAP PDU. */
#                   #define BT_L2CAP_RX_MTU (CONFIG_BT_BUF_ACL_RX_SIZE - BT_L2CAP_HDR_SIZE)
#
#  Anyway, it seems that it would be a good idea to calculate the right number and set a BUILD_ASSERT to check it.
#  So far 3 still works for my 256 bytes characteristic. i should try shorter and longer ones, and measure current consumption too.
#
CONFIG_BT_ATT_PREPARE_COUNT=3
CONFIG_BT_SMP_LOG_LEVEL_DBG=y

#####################
## trying to make auth_oob_data_request work
CONFIG_SETTINGS=y # Needed for CONFIG_BT_SETTINGS
CONFIG_BT_SETTINGS=y # BLE will take care of storing (and restoring) the Bluetooth state (e.g. pairing keys) and configuration persistently in flash
CONFIG_BT_SMP_APP_PAIRING_ACCEPT=y  # Accept pairing requests from the application
CONFIG_BT_SMP_SC_PAIR_ONLY=n  # Disables LE legacy pairing, so only Secure Connections pairing is used
CONFIG_BT_BONDABLE=y
# CONFIG_BT_BONDING_REQUIRED=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y # Needed for Bluetooth storage (Non-volatile storage)

# CONFIG_BT_LOG_LEVEL_DBG=y
# CONFIG_BT_PHY_UPDATE=n
# CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_AUTO_PHY_UPDATE=y
# #################

CONFIG_APP_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y

# for OOB data, testing
CONFIG_BT_TESTING=y
CONFIG_BT_OOB_DATA_FIXED=y
CONFIG_BT_USE_DEBUG_KEYS=y

CONFIG_DEBUG_OPTIMIZATIONS=y
