CONFIG_BT=y
CONFIG_BT_SMP=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_DEVICE_NAME="Central test cert"

CONFIG_LOG=y
CONFIG_BT_GATT_CLIENT=y

# CONFIG_BT_BUF_ACL_RX_SIZE=255
# CONFIG_BT_BUF_ACL_TX_SIZE=251
# CONFIG_BT_BUF_CMD_TX_SIZE=255
# CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=255
# 
# CONFIG_BT_L2CAP_TX_MTU=247

## Number of buffers available for ATT prepare write, setting this to 0 disables GATT long/reliable writes.
#zephyr/doc/connectivity/bluetooth/api/audio/bluetooth-le-audio-arch.rst
#Read long Characteristic Value by setting :kconfig:option:`CONFIG_BT_ATT_PREPARE_COUNT` to a non-zero value.
CONFIG_BT_ATT_PREPARE_COUNT=3
# CONFIG_BT_ATT_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=2048

CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_BT_SMP_LOG_LEVEL_DBG=y

####################
## trying to make auth_oob_data_request work
CONFIG_SETTINGS=y # Needed for CONFIG_BT_SETTINGS
CONFIG_BT_SETTINGS=y # BLE will take care of storing (and restoring) the Bluetooth state (e.g. pairing keys) and configuration persistently in flash
CONFIG_BT_SMP_APP_PAIRING_ACCEPT=y  # Accept pairing requests from the application
CONFIG_BT_SMP_SC_PAIR_ONLY=n  # Disables LE legacy pairing, so only Secure Connections pairing is used
CONFIG_BT_BONDABLE=y
# CONFIG_BT_BONDING_REQUIRED=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y # Needed for Bluetooth storage (Non-volatile storage)

# CONFIG_BT_LOG_LEVEL_DBG=y
# CONFIG_BT_PHY_UPDATE=n
# CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_AUTO_PHY_UPDATE=y

# #################


# CONFIG_BT_LOG_LEVEL_DBG=y
# CONFIG_BT_PRIVACY=y
CONFIG_BT_TESTING=y
# CONFIG_BT_OOB_DATA_FIXED=y
CONFIG_BT_USE_DEBUG_KEYS=y

CONFIG_DEBUG_OPTIMIZATIONS=y
